### ISSUE TITLE
variable.tf of module cce version 4.2.2 not campatible with Terraform version 1.3.2

### ISSUE THREAD

**Issue by prkumar-tsi** [iits-consulting/terraform-opentelekomcloud-project-factory#58]
With Terraform version 1.3.2 , trying to create CCE version 4.2.2, we get below error
Error: Call to unknown function
│ 
│   on variables.tf line 46, in locals:
│   46:   cluster_config = defaults(var.cluster_config, {
│   47:     cluster_type           = "VirtualMachine"
│   48:     cluster_size           = "small"
│   49:     container_network_type = var.cluster_config.cluster_type == "VirtualMachine" || var.cluster_config.cluster_type == null ? "vpc-router" : "underlay_ipvlan"
│   50:     container_cidr         = "172.16.0.0/16"
│   51:     service_cidr           = "10.247.0.0/16"
│   52:     high_availability      = false
│   53:     enable_scaling         = false
│   54:     install_icagent        = false
│   55:   })
│     ├────────────────
│     │ var.cluster_config is a object
│     │ var.cluster_config.cluster_type is a string
│ 
│ **There is no function named "defaults".**

**Comment by victorgetz** [comment]
Hi we did not updated to terraform 1.3.X yet and there are some breaking changes. But i think we will be able to bring out a new release with terraform 1.3.X either this or next week.

**Comment by victorgetz** [comment]
Release 5.0.0 is out now
