### ISSUE TITLE
Improvement: Modify node pools - changes without downtime

### ISSUE THREAD

**Issue by k11h-de** [iits-consulting/terraform-opentelekomcloud-project-factory#62]
Hi iits team,

as always: thanks a million for all your work and effort in this. 

We have following question:
In case we what to change the node flavor or operation system version, all nodes in all node pools are replaced. By default this is done all at once in parallel in terraform - which causes a downtime.
Do you see any chance to ensure the nodes are replaced without downtime?

My idea was to use the [create_before_destroy](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#create_before_destroy) meta argument in the node pool resource.
I was able to test this successfully -- e.g. it is possible to have two node pools named "mycluster-nodes-eu-de-03".

Thanks in advance.
Karsten

**Comment by PhilipSiemerIITS** [comment]
Hi Karsten,
Thank you very much for bringing this up and providing the PR. Using the create_before_destroy argument is a good solution and I can't add any more to it ;) 
It's merged and released as v5.0.1!

Best regards,
Philip
