### ISSUE TITLE
RDS: CES alarm rule for PostgreSQL and SQL Server does not work

### ISSUE THREAD

**Issue by barbara-verso** [iits-consulting/terraform-opentelekomcloud-project-factory#95]
The Cloud Eye alarm rule (``db_storage_alarm_threshold``) does not work for other databases than MySQL.

In ``modules/rds/database.tf`` the ``name`` in ``dimensions`` for ``"db_storage_alarm"`` must be:
- ``postgresql_instance_id`` for PostgreSQL (https://docs.otc.t-systems.com/relational-database-service/umn/working_with_rds_for_postgresql/metrics_and_alarms/configuring_displayed_metrics.html)
- ``rds_instance_sqlserver_id`` for SQL Server (https://docs.otc.t-systems.com/relational-database-service/umn/working_with_rds_for_sql_server/metrics_and_alarms/configuring_displayed_metrics.html)
- and ``rds_instance_id`` for MySQL (https://docs.otc.t-systems.com/relational-database-service/umn/working_with_rds_for_mysql/metrics_and_alarms/configuring_displayed_metrics.html)

**Comment by victorgetz** [comment]
Thank you for your report we will take a look at that

**Comment by canaykin** [comment]
Hi @barbara-verso,

Thank you for reporting this issue. 

I have added the necessary changes and created a pull request. As soon as a second person can approve the changes, they will be merged and included in the next release. 

Best,
Can.
